### ISSUE TITLE
Exportfunktion

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/crashes-shiny#20]
Eine Funktion, die es erlaubt, die Rohdaten zu den aktuellen Filtereinstellungen z.B. als CSV herunterzuladen.

**Comment by ubergesundheit** [comment]
Ich glaube dafür würde ich einen separaten service basteln so ähnlich wie die [Helfer](https://github.com/codeformuenster/verkehrsunfaelle/tree/master/editor-data-helpers) die ich für den editor gebaut habe. Würde vermeiden dass die ganzen Daten einmal durch Shiny durch müssen..

**Comment by silberzwiebel** [comment]
Gute Idee! Shiny würde also die Filtereinstellungen an so einen Helfer übergeben, und der gibt eine entsprechende CSV zurück?

**Comment by ubergesundheit** [comment]
Genau. Die Filtereinstellungen würden dann einem HTTP request an den Service gesendet, welcher dann die CSV dem Benutzer zum download anbietet.
