### ISSUE TITLE
mehrere Unfälle an exakt gleichem Ort: nicht auswählbar

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/crashes-shiny#22]
irgendwie eine kluge Möglichkeit schaffen, dass man sich alle Unfälle am exakt gleichen Ort anschauen kann. Vielleicht Unfälle-Geodaten leicht random-mäßig bewegen in Umkreis von 10 Metern?

**Comment by ubergesundheit** [comment]
Geht entweder mit: https://github.com/Leaflet/Leaflet.markercluster oder https://github.com/jawj/OverlappingMarkerSpiderfier-Leaflet

**Comment by silberzwiebel** [comment]
Danke, sollte also so z.B. funktionieren:

```
  addMarkers(data=quakes, clusterOptions = markerClusterOptions())
```

Teste ich morgen aus!
