### ISSUE TITLE
Einklappen der Filter für größere Karte

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/crashes-shiny#26]

**Comment by ubergesundheit** [comment]
Auf breiten Geräten könnten die Karte und die Filter auch nebeneinander sein?

**Comment by silberzwiebel** [comment]
Leaflet resizen ist relativ kompliziert. Jetzt ist die Karte einfach direkt größer. Dadurch entfällt auch die Notwendigkeit des Einklappens der Filter.
CC @sandzwerg (ist noch nicht online, aber bald)
